$('#banner').slick({
    autoplay:true,
    autoplaySpeed:1500,
    arrows:false
});
$('#brand').slick({
    slidesToShow:4,
    autoplay:true,
    autoplaySpeed:1000,
    dots:true,
    arrows:false
});